DROP TABLE RECAUDO_CORPORATIVO;
CREATE TABLE RECAUDO_CORPORATIVO AS (
SELECT
TO_NUMBER(TO_CHAR(A.FECHA_PAGO,'YYYYMM'))AS "PERIODO",
A.RUC_DNI AS RUC, 
INITCAP(CASE WHEN CAE.RAZON_SOCIAL IS NOT NULL THEN CAE.RAZON_SOCIAL ELSE RZ.RAZON_SOCIAL END)RAZON_SOCIAL,
A.CODIGO                       AS CUENTA,
CU.ORIG_SYSTEM_REFERENCE        AS CUSTOMER_ID,
A.ORIGEN                       AS SERVICIO_ORIGEN,
INITCAP(CASE WHEN A.TIPO_3='MOVIL' THEN 'MÓVIL' ELSE 'FIJA' END)AS TIPO_SERVICIO,
A.DESCRIPTION                  AS DESCRIPCION,
A.NRO_DOC                      AS NRO_DOC,
A.ID_FAC                       AS ID_FAC,
A.CUSTOMER_TRX_ID              AS CUSTOMER_TRX_ID,
INITCAP(A.DEPARTAMENTO)        AS DEPARTAMENTO,
INITCAP(A.ZONAL)               AS "REGION",
C.ENTIDAD                      AS ENTIDAD,
INITCAP((CASE WHEN G.GRUPO IS NOT NULL THEN G.GRUPO ELSE 'Sin Grupo' END))GRUPO,
INITCAP(P.DIRECCION)DIRECCION,
INITCAP(P.SEGMENTO)SEGMENTO,
INITCAP(P.SUB_SEGMENTO)SUB_SEGMENTO,
(CASE WHEN TIPO_4 = 'MASIVO' THEN 'Masivo' 
      WHEN TIPO_4 = 'CORPORATIVO' AND TIPO_CORPORATIVO IN('CARTERIZADO','NO CARTERIZADO') THEN 'Empresas'
      WHEN TIPO_4 = 'CORPORATIVO' AND TIPO_CORPORATIVO = 'GOBIERNO' THEN 'Gobierno' END) TIPO_CORPORATIVO,
INITCAP(A.TIPO_CORPORATIVO)    AS SEGMENTO_CORP,
A.PRODUCTO              AS TIPO_TECNOLOGIA,
A.EMI                   AS EMISION,
A.VENC                  AS VENCIMIENTO,
A.SALDO_PENDIENTE_SOLES AS DEUDA_SOLES,          
A.MONEDA, 
A.NRO_PAGO,    
A.MONTO_APLIC           AS MONTO_APLICADO,
A.MONTO_SOLES           AS PAGOS_SOLES,
A.FECHA_PAGO            AS FECHA_PAGO,
A.FECHA_APLIC           AS FECHA_APLICADA,
INITCAP(A.ESTADO_CONTABLE)ESTADO_CONTABLE,
INITCAP(A.ESTADO_PAGO)ESTADO_PAGO,
A.DIA                        AS DIA,
TO_CHAR(A.FECHA_PAGO,'MM')   AS MES,
TO_CHAR(A.FECHA_PAGO,'YYYY') AS "AÑO",
INITCAP(A.DIA_PAGO)                   AS DIA_PAGO,
A.DIA||' ' ||INITCAP(A.DIA_PAGO)      AS CONCA,
A.RECAUDADOR                 AS RECAUDADOR,
(CASE WHEN A.DEBITO='NO ES DEBITO' THEN 'No es débito' ELSE 'Débito' END)DEBITO,
A.ANTIGUEDAD,
CASE WHEN A.FECHA_PAGO - TRUNC(A.VENC) <1   THEN  '1. Por vencer'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <31  THEN  '2. 1 a 30'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <61  THEN  '3. 31 a 60'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <91  THEN  '4. 61 a 90'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <121 THEN  '5. 91 a 120'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <151 THEN  '6. 121 a 150'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <211 THEN  '7. 151 a 210'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) <365 THEN  '8. 211 a 364'
     WHEN A.FECHA_PAGO - TRUNC(A.VENC) >=365 THEN '9. 365 a más' END TRAMO_RECAUDO,
INITCAP((CASE WHEN (B.TIPO IS NULL OR B.TIPO='NO OPERADOR')THEN 'NO OPERADOR' ELSE 'OPERADOR'END ))OPERADOR,
(CASE WHEN TIPO_CORPORATIVO ='CARTERIZADO'    AND TOP_600 IS NOT NULL THEN 'Top'
      WHEN TIPO_CORPORATIVO ='CARTERIZADO'    AND TOP_600 IS NULL THEN 'No Top'
      WHEN TIPO_CORPORATIVO ='NO CARTERIZADO' AND TIPO_DOC_ORIGEN IN ('DNI','RUC 10')THEN 'RUC 10'
      WHEN TIPO_CORPORATIVO ='NO CARTERIZADO' AND TIPO_DOC_ORIGEN IN ('RUC 20','RUC 17','RUC 15')THEN 'RUC 20' ELSE '-'
      END) TIPO_CLIENTE_CORP,    
 (CASE WHEN A.ATTRIBUTE2 = '12' THEN 'Bancos - Transferencia' 
            WHEN A.ATTRIBUTE2 = '11' and C.TIPO = 'Bancos' then 'Débito Automático por TD'
            ELSE C.TIPO
         END )AS TIPO_RECAUDO,
(CASE WHEN C.TIPO IN('CAC','Autoatención','Establecimientos','DAC - CRL') THEN 'Presencial'
     WHEN C.TIPO IN('MiClaro','Débito Automático') THEN 'En línea'
     WHEN C.TIPO = 'Bancos' AND A.P_NUMERO_COMERCIO = '111017' then 'Presencial' 
     WHEN C.TIPO = 'Bancos' AND A.RECAUDADOR = '621700' THEN 'Presencial' 
     WHEN C.TIPO = 'Bancos' AND A.RECAUDADOR IN ('624700','624800','641000','631000','622700') THEN 'Presencial' 
     WHEN C.TIPO = 'Bancos' and A.P_COD_CANAL IN ('02','14','90','54') THEN 'Presencial'
     WHEN C.TIPO = 'Bancos' and A.P_COD_CANAL IN ('07','15') THEN 'En línea'
          ELSE 'En línea'        
     END )AS CANAL,
TO_DATE(SYSDATE-1,'DD/MM/YY') FECHA_ACTUALIZACION
FROM OPERACION.IRC_RECAUDO_TP_19_DETA A ,
DMRED.HZ_CUST_ACCOUNTS@DBL_DWO CU,
OPERACION.IRC_RECAUDO_WL_OPER B,
OPERACION.T_RECAUDADOR C,
(SELECT DISTINCT RUC,MAX(RAZON_SOCIAL)RAZON_SOCIAL FROM CONTATEMP.MC_DS_CARTERA_CAE@DBL_DWO GROUP BY RUC)CAE,
(SELECT DISTINCT RUC_DNI,MAX(NOMBRE_CLIENTE)RAZON_SOCIAL FROM OPERACION.IRC_RECAUDO_TP_19_DETA A WHERE 1=1
AND TO_NUMBER(TO_CHAR(A.FECHA_PAGO,'YYYY'))>='2022'
AND A.RECAUDADOR NOT IN ('660800')
AND TIPO_4='CORPORATIVO' 
GROUP BY RUC_DNI)RZ ,
C13023.PIRAMIDE_NEW@DBL_DWO P,
C13023.ICC_GRUPOS_ECONOMICOS@DBL_DWO G
WHERE 1=1
AND A.CODIGO=CU.ACCOUNT_NUMBER(+)
AND A.RUC_DNI=B.RUC(+)
AND RZ.RUC_DNI(+)=A.RUC_DNI
AND P.NUMDOC(+) = A.RUC_DNI
AND G.RUC(+) = A.RUC_DNI
AND CAE.RUC(+)=A.RUC_DNI
AND C.RECAUDADOR(+) = A.RECAUDADOR
AND A.RECAUDADOR NOT IN ('660800')
AND TO_NUMBER(TO_CHAR(A.FECHA_PAGO,'YYYY'))>='2022'
AND TIPO_4='CORPORATIVO');
-------------------------------------------------------AGREGAR_CAMPOS----------------------------------------------------
ALTER TABLE RECAUDO_CORPORATIVO ADD WHITELIST VARCHAR(20);
ALTER TABLE RECAUDO_CORPORATIVO ADD PLAZO_ESPECIAL VARCHAR2(20);
ALTER TABLE RECAUDO_CORPORATIVO ADD ESTADO VARCHAR2(200);
ALTER TABLE RECAUDO_CORPORATIVO ADD REGION2 VARCHAR2(20);
ALTER TABLE RECAUDO_CORPORATIVO ADD DEPARTAMENTO2 VARCHAR2(200);
ALTER TABLE RECAUDO_CORPORATIVO ADD PROVINCIA VARCHAR2(200);
ALTER TABLE RECAUDO_CORPORATIVO ADD DISTRITO VARCHAR2(200);
ALTER TABLE RECAUDO_CORPORATIVO ADD GESTOR VARCHAR2(100);
ALTER TABLE RECAUDO_CORPORATIVO ADD NOMBRE_CARTERA VARCHAR2(200);
-------------------------------------------------------CRUCES_CARTERA_CARTERAZADO_Y_GOBIERNO----------------------------------------------------
MERGE INTO RECAUDO_CORPORATIVO D
USING (SELECT X.* FROM (SELECT  RUC_DNI ,NOMBRE_CARTERA, GESTOR ,
ROW_NUMBER() OVER (PARTITION BY RUC_DNI ORDER BY SEGMENTO DESC,FECHA DESC,NOMBRE_CARTERA DESC,GESTOR DESC)RN 
FROM OPERACION.IRC_MSQL_LIQ_CONSOLIDADOS WHERE (CASE WHEN AFILIADOS_AFP IS NOT NULL THEN AFILIADOS_AFP ELSE TIPO_CORPORATIVO END) NOT IN ('NO CARTERIZADO'))X
WHERE RN=1) A ON ( A.RUC_DNI = D.RUC)
WHEN MATCHED THEN UPDATE SET 
     D.NOMBRE_CARTERA=A.NOMBRE_CARTERA,
     D.GESTOR = A.GESTOR;
-------------------------------------------------------CRUCES_CARTERA_NO_CARTERIZADO----------------------------------------------------
MERGE INTO (SELECT * FROM RECAUDO_CORPORATIVO WHERE NOMBRE_CARTERA IS NULL)  D
USING  (SELECT X.* FROM (SELECT  CUST_ACCOUNT ,NOMBRE_CARTERA, GESTOR ,
ROW_NUMBER() OVER (PARTITION BY CUST_ACCOUNT ORDER BY SEGMENTO DESC,FECHA DESC,NOMBRE_CARTERA DESC,GESTOR DESC)RN 
FROM OPERACION.IRC_MSQL_LIQ_CONSOLIDADOS WHERE (CASE WHEN AFILIADOS_AFP IS NOT NULL THEN AFILIADOS_AFP ELSE TIPO_CORPORATIVO END)='NO CARTERIZADO')X
WHERE RN=1) A ON ( A.CUST_ACCOUNT = D.CUENTA)
WHEN MATCHED THEN UPDATE SET 
     D.NOMBRE_CARTERA=A.NOMBRE_CARTERA,
     D.GESTOR = A.GESTOR;
-------------------------------------------------------CRUCES_PLAZO_ESPECIAL----------------------------------------------------
MERGE INTO RECAUDO_CORPORATIVO D
USING (SELECT *FROM C18571.CORP_CLIENTES_ESPECIALES WHERE FECHA_FIN IS NULL) P ON (P.RUC = D.RUC )
WHEN MATCHED THEN UPDATE SET D.PLAZO_ESPECIAL=P.PLAZO;
-------------------------------------------------------CRUCE_WHITELIST----------------------------------------------------
MERGE INTO RECAUDO_CORPORATIVO D
USING (SELECT T.* FROM (SELECT DISTINCT RUC,'SI'WHITELIST ,ROW_NUMBER() OVER (PARTITION BY RUC ORDER BY F_DUMP DESC)RN
FROM USRIRC.IRC_NOTIF_BL_P_RAW@DBL_DWO )T WHERE RN=1) U ON (U.RUC = D.RUC )
WHEN MATCHED THEN UPDATE SET 
  D.WHITELIST = U.WHITELIST;
UPDATE RECAUDO_CORPORATIVO SET WHITELIST = 'NO' WHERE WHITELIST IS NULL;
-------------------------------------------------------CRUCE_REGION_DEPARTAMENTO_PROVINCIA_DISTRITO----------------------------------------------------
MERGE INTO RECAUDO_CORPORATIVO D
USING (SELECT C.CUENTA_CD ,UPPER(Z.ZONAL) REGION, C.DEPARTAMENTO_CUENTA_DESC, C.PROVINCIA_CUENTA_DESC,C. DISTRITO_CUENTA_DESC,ESTADO_CUENTA_DESC FROM DWHDS.DS_CUENTAS@DBL_DWO C ,RC_ZONALES Z
WHERE UPPER(C.DEPARTAMENTO_CUENTA_DESC)= UPPER(Z.DEPARTAMENTO))
 U ON (U.CUENTA_CD = D.CUSTOMER_ID )
WHEN MATCHED THEN UPDATE SET 
  D.REGION2=UPPER(U.REGION),
  D.DEPARTAMENTO2 = UPPER(U.DEPARTAMENTO_CUENTA_DESC),
  D.PROVINCIA = UPPER(U.PROVINCIA_CUENTA_DESC),
  D.DISTRITO = UPPER(U.DISTRITO_CUENTA_DESC),
  D.ESTADO=U.ESTADO_CUENTA_DESC;
-------------------------------------------------------AGREGAR_CAMPO_DE_CADA_TRAMO----------------------------------------------------
ALTER TABLE RECAUDO_CORPORATIVO ADD "1. Por vencer" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "2. 1 a 30" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "3. 31 a 60" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "4. 61 a 90" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "5. 91 a 120" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "6. 121 a 150" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "7. 151 a 210" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "8. 211 a 364" NUMBER;
ALTER TABLE RECAUDO_CORPORATIVO ADD "9. 365 a más" NUMBER;
-------------------------------------------------------CRUCE_TRAMO----------------------------------------------------
UPDATE RECAUDO_CORPORATIVO R
SET   
"1. Por vencer" =(CASE WHEN R.TRAMO_RECAUDO='1. Por vencer' THEN R.PAGOS_SOLES ELSE 0 END),
"2. 1 a 30" =(CASE WHEN R.TRAMO_RECAUDO='2. 1 a 30' THEN R.PAGOS_SOLES ELSE 0 END),
"3. 31 a 60" =(CASE WHEN R.TRAMO_RECAUDO='3. 31 a 60' THEN R.PAGOS_SOLES ELSE 0 END),
"4. 61 a 90" =(CASE WHEN R.TRAMO_RECAUDO='4. 61 a 90' THEN R.PAGOS_SOLES ELSE 0 END),
"5. 91 a 120" =(CASE WHEN R.TRAMO_RECAUDO='5. 91 a 120' THEN R.PAGOS_SOLES ELSE 0 END),
"6. 121 a 150" =(CASE WHEN R.TRAMO_RECAUDO='6. 121 a 150' THEN R.PAGOS_SOLES ELSE 0 END),
"7. 151 a 210"  =(CASE WHEN R.TRAMO_RECAUDO='7. 151 a 210' THEN R.PAGOS_SOLES ELSE 0 END),
"8. 211 a 364"  =(CASE WHEN R.TRAMO_RECAUDO='8. 211 a 364' THEN R.PAGOS_SOLES ELSE 0 END),
"9. 365 a más"  =(CASE WHEN R.TRAMO_RECAUDO='9. 365 a más' THEN R.PAGOS_SOLES ELSE 0 END);
-------------------------------------------------------FECHA_ACTUALIZACION----------------------------------------------------
ALTER TABLE RECAUDO_CORPORATIVO ADD F_DUMP DATE;
UPDATE RECAUDO_CORPORATIVO SET
F_DUMP =SYSDATE;
GRANT SELECT ON USRRCC.RECAUDO_CORPORATIVO TO USRPOWERBI;
GRANT SELECT ON USRRCC.RECAUDO_CORPORATIVO TO C13911;
GRANT SELECT ON USRRCC.RECAUDO_CORPORATIVO TO C10533;